import '@/styles/globals.css'
import type { AppProps } from 'next/app'
import Head from 'next/head'
import { logo } from '../utils/constants'

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>Nuor</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={logo} />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
        />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <Component {...pageProps} />
    </>
  )
}
